language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
spring:
   jpa:
     properties:
       hibernate:
         jdbc:
           time_zone = BRT
services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('ruvv47@') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root